import type { ExerciseDefinition } from "./start-contract";

// 1. Shared demo and presentation settings
export const START_SETTINGS = {
  demonstrationCueSeconds: 2,
  completeVoice: {
    url: "/audio/tutorial/de/complete.wav",
    durationSeconds: 13.861479,
    instructionAtSeconds: 0,
  },
  showFlightGuidance: false,
  pathOpacity: 0.22,
  retireSeconds: 2.5,
  belowFlightMeters: 0.5,
  seed: 17,
  entryLineMeters: 20,
  entryBehindMeters: 4,
  recoveryLeadMeters: 6,
  keepPathBehindMeters: 12,
  pathPoolSize: 4,
  elementPoolSize: 4,
  generationMetersPerStep: 4,
  revealSeconds: 0.8,
  elementAnimation: {
    revealSeconds: 1.3,
    dissolveSeconds: 1.2,
    scatterMeters: 0.8,
  },
  elementLight: {
    capacity: 24,
    periodSeconds: 3.4,
    sweepSeconds: 1.4,
    staggerSeconds: 0.18,
    guideStrength: 0.6,
    lightGain: 3.2,
    lightSizeBoost: 0.8,
    glintStrength: 0.45,
    flashSeconds: 0.85,
    bandWidth: 0.3,
    glassFraction: 0.32,
    color: 0xfb5f16,
  },
  elementRetirement: { capacity: 24, dissolveSeconds: 1.2, clearanceMeters: 2 },
  elementPassage: { maximumStepMeters: 3 },
  elementSimulation: {
    radiusMeters: 5.2,
    impulse: 4,
    spring: 3,
    damping: 2.2,
    maximumStepMeters: 3,
    maximumOffsetMeters: 0.8,
    maximumDeltaSeconds: 0.05,
  },
  elementWind: {
    horizontalAmplitudeMeters: 0.4,
    verticalAmplitudeMeters: 0.25,
    speedMultiplier: 1.8,
  },
  arrowVolume: { haloFraction: 0, coreRadiusMeters: 0.4 },
  elementVolume: {
    coreRadiusMeters: 0.55,
    haloRadiusMeters: 1.2,
    haloFraction: 0.18,
    coreOpacity: 0.72,
    coreSizeScale: 1.35,
    haloSizeScale: 0.7,
    relief: 0.12,
    grainsPerSample: 12,
    grainSpreadMeters: 0.14,
    accentFraction: 0.06,
    haloOpacity: { from: 0.08, to: 0.3 },
    seed: 137,
  },
  elementParticles: {
    densityPerMeter: { from: 64, to: 80 },
    color: { from: 0x000000, to: 0x000000 },
    sizeMeters: { from: 0.03, to: 0.06 },
    spreadMeters: 0,
    seed: 43,
  },
};

// 2. Exercise sequence
// Speech order is right, left, climb, descent. Praise requires prior success.
// Radius tuning: new spacing / (old spacing / old radius + radians(5)).
// All lengths are meters. Ring spacing is 70% of the previous course;
// Entry/exit lengths are halved. Speech, emergence timing and flight speed stay intact.
export const START_EXERCISES = [
  {
    id: "right",
    sequence: {
      approachMeters: 12,
      pathAtSeconds: 14.4,
      worldReveal: { atSeconds: 13.12, fadeSeconds: 3.2 },
    },
    voice: {
      url: "/audio/tutorial/de/introduction-right.wav",
      durationSeconds: 20.725729,
      instructionAtSeconds: 19.3,
    },
    route: {
      leadMeters: 0,
      straightMeters: 3,
      outroMeters: 9,
      turnSign: 1,
      turnRadiusMeters: { from: 16.6041, to: 18.0944 },
      turnDegrees: { from: 110, to: 110 },
    },
    particles: {
      densityPerMeter: { from: 40, to: 68 },
      color: { from: 0x2c858d, to: 0x77bec2 },
      sizeMeters: { from: 0.025, to: 0.055 },
      spreadMeters: 0.55,
      seed: 17,
    },
    elements: {
      showArrows: false,
      entryArrow: { distanceMeters: 12, aboveMeters: 1.8, sideMeters: -5 },
      ringCount: 3,
      firstMeters: 20,
      spacingMeters: 5.6,
      ringRadiusMeters: 3.6,
      arrowLengthMeters: 4.8,
      arrowOffsetMeters: 7,
      arrowPhaseFraction: 0.5,
    },
    deviation: {
      distanceMeters: 12,
      outsideTravelMeters: 8,
      directionDifferenceRadians: 0.87,
      lookAheadMeters: 20,
      visibilityPaddingMeters: 6,
      maximumStepMeters: 3,
    },
    progress: {
      checkpointSpacingMeters: 2,
      toleranceMeters: 12,
      extraTravelMeters: 7,
      maximumStepMeters: 3,
    },
  },
  {
    id: "left",
    sequence: { approachMeters: 10 },
    voice: {
      url: "/audio/tutorial/de/left.wav",
      durationSeconds: 2.735417,
      instructionAtSeconds: 1.14,
    },
    route: {
      leadMeters: 0,
      straightMeters: 4,
      outroMeters: 12,
      turnSign: -1,
      turnRadiusMeters: { from: 17.5102, to: 19.1758 },
      turnDegrees: { from: 120, to: 120 },
    },
    particles: {
      densityPerMeter: { from: 40, to: 68 },
      color: { from: 0x2c858d, to: 0x77bec2 },
      sizeMeters: { from: 0.025, to: 0.055 },
      spreadMeters: 0.55,
      seed: 17,
    },
    elements: {
      showArrows: false,
      ringCount: 6,
      firstMeters: 4,
      spacingMeters: 7,
      ringRadiusMeters: 3.6,
      arrowLengthMeters: 4.6,
      arrowOffsetMeters: 7,
      arrowPhaseFraction: 0.5,
    },
    deviation: {
      distanceMeters: 12,
      outsideTravelMeters: 8,
      directionDifferenceRadians: 0.87,
      lookAheadMeters: 20,
      visibilityPaddingMeters: 6,
      maximumStepMeters: 3,
    },
    progress: {
      checkpointSpacingMeters: 2,
      toleranceMeters: 12,
      extraTravelMeters: 7,
      maximumStepMeters: 3,
    },
  },
  {
    id: "up",
    sequence: { approachMeters: 10 },
    voice: {
      url: "/audio/tutorial/de/up.wav",
      durationSeconds: 4.334896,
      instructionAtSeconds: 2.66,
    },
    route: {
      turnPlane: "vertical",
      leadMeters: 0,
      straightMeters: 6,
      outroMeters: 12,
      turnSign: 1,
      turnRadiusMeters: { from: 32.9774, to: 33.9289 },
      turnDegrees: { from: 32, to: 32 },
    },
    particles: {
      densityPerMeter: { from: 40, to: 68 },
      color: { from: 0x2c858d, to: 0x77bec2 },
      sizeMeters: { from: 0.025, to: 0.055 },
      spreadMeters: 0.55,
      seed: 17,
    },
    elements: {
      showArrows: false,
      ringCount: 6,
      firstMeters: 6,
      spacingMeters: 7,
      ringRadiusMeters: 3.6,
      arrowLengthMeters: 4.6,
      arrowOffsetMeters: 7,
      arrowPhaseFraction: 0.5,
    },
    deviation: {
      distanceMeters: 12,
      outsideTravelMeters: 8,
      directionDifferenceRadians: 0.87,
      lookAheadMeters: 20,
      visibilityPaddingMeters: 6,
      maximumStepMeters: 3,
    },
    progress: {
      checkpointSpacingMeters: 2,
      toleranceMeters: 12,
      extraTravelMeters: 7,
      maximumStepMeters: 3,
    },
  },
  {
    id: "down",
    sequence: { approachMeters: 10 },
    voice: {
      url: "/audio/tutorial/de/down.wav",
      durationSeconds: 2.552583,
      instructionAtSeconds: 1.04,
    },
    route: {
      turnPlane: "vertical",
      leadMeters: 0,
      straightMeters: 6,
      outroMeters: 12,
      turnSign: -1,
      turnRadiusMeters: { from: 32.9774, to: 33.9289 },
      turnDegrees: { from: 32, to: 32 },
    },
    particles: {
      densityPerMeter: { from: 40, to: 68 },
      color: { from: 0x2c858d, to: 0x77bec2 },
      sizeMeters: { from: 0.025, to: 0.055 },
      spreadMeters: 0.55,
      seed: 17,
    },
    elements: {
      showArrows: false,
      ringCount: 6,
      firstMeters: 6,
      spacingMeters: 7,
      ringRadiusMeters: 3.6,
      arrowLengthMeters: 4.6,
      arrowOffsetMeters: 7,
      arrowPhaseFraction: 0.5,
    },
    deviation: {
      distanceMeters: 12,
      outsideTravelMeters: 8,
      directionDifferenceRadians: 0.87,
      lookAheadMeters: 20,
      visibilityPaddingMeters: 6,
      maximumStepMeters: 3,
    },
    progress: {
      checkpointSpacingMeters: 2,
      toleranceMeters: 12,
      extraTravelMeters: 7,
      maximumStepMeters: 3,
    },
  },
] as const satisfies readonly ExerciseDefinition[];
