import type { ExerciseDefinition } from "./start-contract";

// 1. Shared demo and presentation settings
export const START_SETTINGS = {
  demonstrationCueSeconds: 2,
  showFlightGuidance: false,
  pathOpacity: 0.22,
  retireSeconds: 1.2,
  belowFlightMeters: 0.5,
  seed: 17,
  entryLeadMeters: 12,
  generationMetersPerStep: 4,
  revealSeconds: 0.8,
  elementAnimation: {
    revealSeconds: 1.3,
    dissolveSeconds: 1.2,
    scatterMeters: 0.8,
  },
  elementLight: {
    capacity: 24,
    periodSeconds: 3.4,
    sweepSeconds: 1.4,
    staggerSeconds: 0.18,
    guideStrength: 0.6,
    lightGain: 3.2,
    lightSizeBoost: 0.8,
    glintStrength: 0.45,
    flashSeconds: 0.85,
    bandWidth: 0.3,
    glassFraction: 0.32,
    color: 0xfb5f16,
  },
  elementRetirement: { capacity: 24, dissolveSeconds: 1.2, clearanceMeters: 2 },
  elementPassage: { maximumStepMeters: 3 },
  elementSimulation: {
    radiusMeters: 5.2,
    impulse: 4,
    spring: 3,
    damping: 2.2,
    maximumStepMeters: 3,
    maximumOffsetMeters: 0.8,
    maximumDeltaSeconds: 0.05,
  },
  elementWind: {
    horizontalAmplitudeMeters: 0.09,
    verticalAmplitudeMeters: 0.055,
    speedMultiplier: 0.45,
  },
  elementVolume: {
    coreRadiusMeters: 0.55,
    haloRadiusMeters: 1.2,
    haloFraction: 0.18,
    coreOpacity: 0.72,
    coreSizeScale: 1.35,
    haloSizeScale: 0.7,
    relief: 0.12,
    grainsPerSample: 12,
    grainSpreadMeters: 0.14,
    accentFraction: 0.06,
    haloOpacity: { from: 0.08, to: 0.3 },
    seed: 137,
  },
  elementParticles: {
    densityPerMeter: { from: 64, to: 80 },
    color: { from: 0x000000, to: 0x000000 },
    sizeMeters: { from: 0.03, to: 0.06 },
    spreadMeters: 0,
    seed: 43,
  },
};

// 2. Exercise sequence
// The MVP demonstrates both turn directions. Narration ordering is authored later.
export const START_EXERCISES = [
  {
    id: "left",
    route: {
      leadMeters: 0,
      straightMeters: 10,
      outroMeters: 24,
      turnSign: -1,
      turnRadiusMeters: { from: 38, to: 46 },
      turnRadians: { from: 0.8, to: 1.05 },
    },
    particles: {
      densityPerMeter: { from: 40, to: 68 },
      color: { from: 0x2c858d, to: 0x77bec2 },
      sizeMeters: { from: 0.025, to: 0.055 },
      spreadMeters: 0.55,
      seed: 17,
    },
    elements: {
      showArrows: false,
      firstMeters: 12,
      spacingMeters: 14,
      ringRadiusMeters: 3.6,
      arrowLengthMeters: 4.6,
      arrowOffsetMeters: 7,
      arrowPhaseFraction: 0.5,
    },
    deviation: {
      distanceMeters: 5,
      outsideTravelMeters: 3,
      maximumStepMeters: 3,
    },
    progress: {
      checkpointSpacingMeters: 2,
      toleranceMeters: 1.4,
      extraTravelMeters: 7,
      maximumStepMeters: 3,
    },
  },
  {
    id: "right",
    route: {
      leadMeters: 0,
      straightMeters: 10,
      outroMeters: 24,
      turnSign: 1,
      turnRadiusMeters: { from: 38, to: 46 },
      turnRadians: { from: 0.8, to: 1.05 },
    },
    particles: {
      densityPerMeter: { from: 40, to: 68 },
      color: { from: 0x2c858d, to: 0x77bec2 },
      sizeMeters: { from: 0.025, to: 0.055 },
      spreadMeters: 0.55,
      seed: 17,
    },
    elements: {
      showArrows: false,
      firstMeters: 12,
      spacingMeters: 14,
      ringRadiusMeters: 3.6,
      arrowLengthMeters: 4.6,
      arrowOffsetMeters: 7,
      arrowPhaseFraction: 0.5,
    },
    deviation: {
      distanceMeters: 5,
      outsideTravelMeters: 3,
      maximumStepMeters: 3,
    },
    progress: {
      checkpointSpacingMeters: 2,
      toleranceMeters: 1.4,
      extraTravelMeters: 7,
      maximumStepMeters: 3,
    },
  },
] as const satisfies readonly ExerciseDefinition[];
