/** Spatial practice; the same recipe supplies standalone and Show training. */
import type { LevelPreset } from "./level-preset";

export const level: LevelPreset = {
  backgroundColor: 0xffffff,
  viewDistance: 128,
  desktopFieldOfViewDegrees: 80,
  maximumGroundClearanceMeters: 50,
  startAudio: {
    samples: [
      { id: "source-01", url: "/audio/granular/atmosphere-grain-01.wav" },
      { id: "source-03", url: "/audio/granular/atmosphere-grain-03.wav" },
      { id: "source-08", url: "/audio/granular/atmosphere-grain-08.wav" },
    ],
    layers: [
      {
        object: "ringLeft",
        sampleId: "source-01",
        grainSizeSeconds: 0.4,
        overlapSeconds: 0.18,
        playbackRate: 0.55,
        volumeDb: -10,
        detuneCents: -700,
        offsetSeconds: 0.5,
      },
      {
        object: "ringRight",
        sampleId: "source-03",
        grainSizeSeconds: 0.3,
        overlapSeconds: 0.12,
        playbackRate: 0.7,
        volumeDb: -13,
        detuneCents: -200,
        offsetSeconds: 4,
      },
      {
        object: "arrow",
        sampleId: "source-08",
        grainSizeSeconds: 0.2,
        overlapSeconds: 0.08,
        playbackRate: 0.4,
        volumeDb: -16,
        detuneCents: 300,
        offsetSeconds: 8,
      },
    ],
    goal: {
      sampleId: "source-03",
      grainSizeSeconds: 0.12,
      overlapSeconds: 0.06,
      playbackRate: 0.8,
      volumeDb: -10,
      detuneCents: 0,
      offsetSeconds: 2,
    },
    referenceDistanceMeters: 4,
    maximumDistanceMeters: 128,
    rolloffFactor: 0.8,
    room: {
      decaySeconds: 8,
      preDelaySeconds: 0.04,
      sendGain: 0.75,
      dryGain: 0.55,
      nearCutoffHz: 9000,
      farCutoffHz: 1400,
      farDistanceMeters: 48,
      speechGain: 0.25,
    },
  },
  start: {
    arrivalSeconds: 2.5,
    formationSeconds: 2,
    dissolutionSeconds: 3,
    goals: [
      { direction: "right", offsetMeters: [12, 0, -32], radiusMeters: 3.5 },
      { direction: "left", offsetMeters: [-12, 0, -92], radiusMeters: 3.5 },
      { direction: "up", offsetMeters: [-12, 16, -152], radiusMeters: 3.5 },
      { direction: "down", offsetMeters: [0, 0, -212], radiusMeters: 3.5 },
    ],
    particles: {
      count: 1400,
      sizeMeters: 0.065,
      color: 0x425563,
      cloudRadiusMeters: 5,
      cloudDepthMeters: 5,
      driftAmplitudeMeters: 0.18,
      driftSpeed: 0.65,
      sparkle: 0.08,
      glow: 0.12,
      wakeRadiusMeters: 8,
      wakeDurationSeconds: 2.4,
      wakeDistanceMeters: 2.5,
    },
  },
  airParticles: {
    density: { particlesPerChunk: 80 },
    appearance: { color: 0x202126, sizeMeters: 0.075 },
    motion: {
      horizontalAmplitudeMeters: 0.12,
      verticalAmplitudeMeters: 0.24,
      speedMultiplier: 1,
    },
  },
};
